import { afterAll, afterEach, beforeAll, beforeEach, expect, it, vi } from "vitest";
import { createSharedPgTaskStoreTestHarness, pgDescribe } from "../../__test-utils__/pg-test-harness.js";
import { ExternalSessionStore } from "../../external-sessions/store.js";
import { ExternalSessionRetention } from "../../external-sessions/retention.js";
import { ExternalSessionSummaries } from "../../external-sessions/summaries.js";
import { externalSessionAnalytics } from "../../external-sessions/analytics.js";
const at = "2026-07-01T12:00:00.000Z", now = Date.parse("2026-09-15T12:00:00.000Z"), cutoff = "2026-08-15T12:00:00.000Z";
const observation = { version: 1, provider: "codex", nativeSessionId: "native", revision: 10, observedAt: at, activity: "waiting", title: "Old work", projectPath: "/repo" };
const turn = { id: "turn", startedAt: at, updatedAt: at, completedAt: at, prompts: ["Prompt"], response: "Collected result", toolCalls: 1, files: [{ path: "a.ts", diff: "+new", added: 1, removed: 0, available: true }], usage: [{ model: "fixture", inputTokens: 10, outputTokens: 2, cachedInputTokens: 0, cacheWriteTokens: 0, cacheWriteHourTokens: 0, requests: 1 }] };
pgDescribe("External session retention", () => {
  const h = createSharedPgTaskStoreTestHarness({ prefix: "fusion_session_retention", projectId: "session-retention-test" });
  beforeAll(h.beforeAll); beforeEach(h.beforeEach); afterEach(async () => { vi.restoreAllMocks(); await h.afterEach(); }); afterAll(h.afterAll);
  it("preserves accounting and notes, protects pinned/linked/recent sessions, and blocks old replay across providers and hosts", async () => {
    const store = new ExternalSessionStore(h.layer()), retention = new ExternalSessionRetention(h.layer()), summaries = new ExternalSessionSummaries(h.layer());
    const ids: string[] = [];
    for (const provider of ["codex", "claude"]) for (const host of ["m3", "m5", "j"]) ids.push((await store.ingest(host, "test", { ...observation, provider }, [turn])).id);
    await summaries.notes(ids[0], "Keep operator notes", 0);
    await store.preferences(ids[1], false, true, 0);
    await store.linkTask(ids[2], "project", "FN-1", true, 0);
    await store.ingest("m3", "test", { ...observation, nativeSessionId: "recent", observedAt: "2026-09-15T00:00:00.000Z" }, [turn]);
    const before = await externalSessionAnalytics(h.layer(), { sessionIds: ids });
    expect((await retention.preview(cutoff, now)).eligibleTurns).toBe(4);
    expect((await store.turn(ids[0], "turn"))?.response).toBe("Collected result");
    expect((await retention.apply(cutoff, now)).removedContentTurns).toBe(4);
    expect(await externalSessionAnalytics(h.layer(), { sessionIds: ids })).toEqual(before);
    const pruned = await store.turn(ids[0], "turn");
    expect(pruned).toMatchObject({ prompts: [], response: "", toolCalls: 1, files: [{ path: "a.ts", diff: "", added: 1, available: false }], contentPruned: { through: at } });
    expect((await summaries.get(ids[0]))?.notes).toBe("Keep operator notes");
    expect((await store.turn(ids[1], "turn"))?.response).toBe("Collected result");
    expect((await store.turn(ids[2], "turn"))?.response).toBe("Collected result");
    await store.ingest("m3", "test", { ...observation, revision: 11 }, [{ ...turn, nativeParserVersion: 6 }]);
    await store.ingest("m3", "import", observation, [turn], true);
    expect((await store.turn(ids[0], "turn"))?.response).toBe("");
    expect((await store.list({ q: "collected" })).sessions.some(row => row.id === ids[0])).toBe(false);
    await store.ingest("m3", "test", { ...observation, revision: 12 }, [{ ...turn, nativeParserVersion: 6, updatedAt: "2026-09-15T00:00:00.000Z", response: "Resumed output" }]);
    expect((await store.turn(ids[0], "turn"))?.response).toBe("Resumed output");
    expect((await store.turn(ids[0], "turn"))?.contentPruned).toBeUndefined();
    expect(await h.store().listTasks()).toHaveLength(0);
  });
  it("bounds each batch, rechecks protection after preview, and rejects unsafe cutoffs", async () => {
    const store = new ExternalSessionStore(h.layer()), retention = new ExternalSessionRetention(h.layer());
    const { id } = await store.ingest("m3", "test", observation, Array.from({ length: 25 }, (_, i) => ({ ...turn, id: String(i) })));
    await store.ingest("m3", "test", { ...observation, revision: 11 }, [{ ...turn, id: "extra" }]);
    expect(await retention.preview(cutoff, now)).toMatchObject({ eligibleTurns: 25, moreAvailable: true });
    await store.preferences(id, true, true, 0);
    expect((await retention.apply(cutoff, now)).removedContentTurns).toBe(0);
    await store.preferences(id, true, false, 1);
    expect(await retention.apply(cutoff, now)).toMatchObject({ removedContentTurns: 25, eligibleTurns: 1 });
    expect(await retention.apply(cutoff, now)).toMatchObject({ removedContentTurns: 1, eligibleTurns: 0 });
    expect((await retention.apply(cutoff, now)).removedContentTurns).toBe(0);
    for (const invalid of ["bad", new Date(now).toISOString(), "2000-01-01T00:00:00Z"]) await expect(retention.apply(invalid, now)).rejects.toThrow("cutoff");
  });
  it("invalidates an in-flight summary and never regenerates summaries from removed content", async () => {
    const store = new ExternalSessionStore(h.layer()), retention = new ExternalSessionRetention(h.layer()), summaries = new ExternalSessionSummaries(h.layer());
    const { id } = await store.ingest("m3", "test", observation, [turn]);
    const send = vi.fn(async () => { await retention.apply(cutoff, now); return new Response(JSON.stringify({ choices: [{ message: { content: "Old result summary" } }] }), { status: 200 }); });
    expect(await summaries.summarize(id, "http://fixture", send, now)).toEqual({ changed: false, reason: "Summary was not saved because its content or lease changed" });
    expect((await summaries.get(id))?.summary).toBeNull();
    expect(await summaries.summarize(id, "http://fixture", send, now)).toMatchObject({ changed: false, reason: "Collected content was removed by retention" });
    expect(send).toHaveBeenCalledTimes(1);
  });
  it("refuses stale summary input when retention commits before lease acquisition", async () => {
    const store = new ExternalSessionStore(h.layer()), retention = new ExternalSessionRetention(h.layer()), summaries = new ExternalSessionSummaries(h.layer());
    const { id } = await store.ingest("m3", "test", observation, [turn]);
    const page = await store.turns(id);
    const spy = vi.spyOn(ExternalSessionStore.prototype, "turns").mockImplementationOnce(async () => { await retention.apply(cutoff, now); return page; });
    const send = vi.fn();
    expect(await summaries.summarize(id, "http://fixture", send, now)).toMatchObject({ changed: false, reason: "Content changed before summary started" });
    expect(send).not.toHaveBeenCalled(); expect((await summaries.get(id))?.summaryLeaseUntil).toBeNull(); spy.mockRestore();
  });
});
