import { afterAll, afterEach, beforeAll, beforeEach, expect, it } from "vitest";
import { createSharedPgTaskStoreTestHarness, pgDescribe } from "../../__test-utils__/pg-test-harness.js";
import { ExternalSessionStore } from "../../external-sessions/store.js";
import { ExternalSessionControls } from "../../external-sessions/controls.js";
import { ExternalSessionSummaries } from "../../external-sessions/summaries.js";
const observation = { version: 1, provider: "codex", nativeSessionId: "n", revision: 1, observedAt: "2026-09-15T12:00:00Z", activity: "working", title: "Fix", projectPath: "/repo" };
const generation = "runtime-generation-1";
pgDescribe("External runtime controls and summaries", () => {
  const h = createSharedPgTaskStoreTestHarness({ prefix: "fusion_external_controls", projectId: "external-control-test" });
  beforeAll(h.beforeAll); beforeEach(h.beforeEach); afterEach(h.afterEach); afterAll(h.afterAll);
  it("observation cannot grant controls; registered host, generation, expiry and idempotency fence delivery", async () => {
    const sessions = new ExternalSessionStore(h.layer()); const controls = new ExternalSessionControls(h.layer());
    const { id } = await sessions.ingest("m3", "test", observation); const now = Date.now();
    await expect(controls.queue(id, "command-id-123456", "stop")).rejects.toThrow("does not support");
    await expect(controls.register("m5", id, generation, ["stop"])).rejects.toThrow("does not belong");
    await controls.register("m3", id, generation, ["feedback"], now);
    const [first, replay] = await Promise.all([1,2].map(() => controls.queue(id, "command-id-123456", "feedback", "Please check", now)));
    expect(first.id).toBe(replay.id); expect(await controls.list(id)).toHaveLength(1);
    expect(await controls.claim("m5", id, generation, now)).toHaveLength(0);
    expect(await controls.claim("m3", id, "other-generation-1", now)).toHaveLength(0);
    expect((await controls.claim("m3", id, generation, now))[0].status).toBe("delivered");
    expect(await controls.acknowledge("m5", first.id, generation, "applied", now)).toBe(false);
    expect(await controls.acknowledge("m3", first.id, generation, "applied", now)).toBe(true);
    expect(await controls.acknowledge("m3", first.id, generation, "applied", now + 1)).toBe(true);
    expect(await controls.acknowledge("m3", first.id, generation, "failed", now + 1)).toBe(false);
    expect(await controls.capability(id, now + 90001)).toMatchObject({ connected: false, capabilities: ["feedback"] });
    expect(await controls.claim("m3", id, generation, now)).toHaveLength(0);
    await controls.queue(id, "command-id-123457", "feedback", "Later", now);
    expect(await controls.claim("m3", id, generation, now + 300001)).toHaveLength(0);
    expect((await controls.list(id)).find(row => row.id === "command-id-123457")?.status).toBe("expired");
    await controls.queue(id, "command-id-123458", "feedback", "Old owner", now);
    await controls.register("m3", id, "replacement-generation-1", ["feedback"], now);
    expect(await controls.claim("m3", id, generation, now)).toHaveLength(0);
  });
  it("summarizes changed content once and preserves the previous summary on an endpoint failure", async () => {
    const sessions = new ExternalSessionStore(h.layer()); const summaries = new ExternalSessionSummaries(h.layer());
    const turn = { id: "turn", startedAt: observation.observedAt, updatedAt: observation.observedAt, completedAt: null, durationMs: null, durationSource: "timestamps", prompts: ["Fix deployment"], response: "Check failed, work unfinished", files: [], usage: [], toolCalls: 1 };
    const { id } = await sessions.ingest("m3", "test", observation, [turn]);
    let calls = 0;
    const send = (async (_url: string, init: RequestInit) => { calls++; const body = JSON.parse(String(init.body)); expect(body.model).toBe("qwen3.5-2b"); expect(body.chat_template_kwargs.enable_thinking).toBe(false); return new Response(JSON.stringify({ choices: [{ message: { content: "Check failed. Deployment is unfinished." } }] }), { status: 200 }); }) as typeof fetch;
    expect((await summaries.summarize(id, "http://localhost/v1", send)).changed).toBe(true);
    expect((await summaries.summarize(id, "http://localhost/v1", send)).changed).toBe(false); expect(calls).toBe(1);
    await sessions.ingest("m3", "test", { ...observation, revision: 2 }, [{ ...turn, response: "Still unfinished; another check failed" }]);
    await summaries.summarize(id, "http://localhost/v1", (async () => new Response("busy", { status: 503 })) as typeof fetch);
    expect((await summaries.get(id))?.summary?.text).toBe("Check failed. Deployment is unfinished.");
    expect((await summaries.get(id))?.summaryFailures).toBe(1);
    expect((await summaries.notes(id, "Note", 0)).notesRevision).toBe(1);
    await expect(summaries.notes(id, "Stale", 0)).rejects.toThrow("revision conflict");
  });
  it("fences native execution durably and refuses takeover or replay after an ambiguous crash", async () => {
    const sessions = new ExternalSessionStore(h.layer()); const controls = new ExternalSessionControls(h.layer());
    const { id } = await sessions.ingest("m3", "test", observation); const now = Date.now();
    expect(await controls.register("m3", id, generation, ["stop", "feedback"], now, "fusion-runtime")).toBe(true);
    expect(await controls.register("m3", id, generation, ["feedback"], now, "host-adapter")).toBe(false);
    expect(await controls.register("m3", id, "replacement-generation-1", ["stop"], now, "fusion-runtime")).toBe(false);
    const command = await controls.queue(id, "native-command-123456", "stop", undefined, now);
    expect(command.controller).toBe("fusion-runtime");
    await controls.claim("m3", id, generation, now);
    expect(await controls.beginExecution("m5", command.id, generation, now)).toBeNull();
    const begun = await Promise.all([controls, new ExternalSessionControls(h.layer())].map(control => control.beginExecution("m3", command.id, generation, now)));
    expect(begun.filter(Boolean)).toHaveLength(1);
    expect(await new ExternalSessionControls(h.layer()).claim("m3", id, generation, now)).toHaveLength(0);
    expect((await controls.list(id, now + 300001))[0].status).toBe("unconfirmed after interruption");
    expect(await controls.acknowledge("m3", command.id, generation, "applied", now + 300001)).toBe(true);
    expect((await controls.list(id))[0].status).toBe("applied");
    expect(await controls.capability(id, now + 90001)).toMatchObject({ connected: false, capabilities: [] });
    await expect(controls.queue(id, "native-command-123457", "feedback", "Late", now + 90001)).rejects.toThrow("disconnected");
    expect(await controls.register("m3", id, "replacement-generation-1", ["stop"], now + 90001, "fusion-runtime")).toBe(true);
  });
  it("records verified native associations without overriding explicit operator unlink intent", async () => {
    const sessions = new ExternalSessionStore(h.layer()); const summaries = new ExternalSessionSummaries(h.layer());
    const { id } = await sessions.ingest("m3", "test", observation);
    await sessions.associateNativeRuntime(id, { cliSessionId: "cli-owned", projectId: "project", taskId: "FN-1" });
    expect(await summaries.get(id)).toMatchObject({ taskId: "FN-1", taskProjectId: "project", taskLinkSource: "native-runtime", nativeRuntime: { cliSessionId: "cli-owned" } });
    await sessions.linkTask(id, "project", "FN-1", false, 1);
    await sessions.associateNativeRuntime(id, { cliSessionId: "cli-resumed", projectId: "project", taskId: "FN-1" });
    expect(await summaries.get(id)).toMatchObject({ taskId: null, taskLinkSource: null, taskLinkRevision: 2, nativeRuntime: { cliSessionId: "cli-resumed" } });
    expect(await h.store().listTasks()).toHaveLength(0);
  });
});
